# Generated by Django 5.1.15 on 2026-09-22 00:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterShareBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='账期月格式须为 YYYY-MM，如 2026-09', regex='^\\d{4}-(0[1-9]|1[0-2])$')])),
                ('price_per_liter', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sealed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_share_bills', to='core.greenhouse')),
            ],
            options={
                'ordering': ['-billing_month', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WaterShareEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.watersharebill')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_entries', to='core.irrigationcycle')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='watersharebill',
            constraint=models.UniqueConstraint(fields=('greenhouse', 'billing_month'), name='uniq_bill_per_greenhouse_month'),
        ),
        migrations.AddConstraint(
            model_name='watershareentry',
            constraint=models.UniqueConstraint(fields=('cycle',), name='uniq_cycle_per_bill_entry'),
        ),
    ]
