# Generated by Django 5.1.15 on 2026-09-22 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.CharField(help_text='账期月，形如 2026-09', max_length=7)),
                ('price_per_liter', models.DecimalField(decimal_places=4, help_text='每升单价（元/升）', max_digits=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_bills', to='core.greenhouse')),
            ],
            options={
                'ordering': ['-period_month', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WaterBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.waterbill')),
                ('irrigation_cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_item', to='core.irrigationcycle')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='waterbill',
            constraint=models.UniqueConstraint(fields=('greenhouse', 'period_month'), name='uniq_water_bill_greenhouse_month'),
        ),
    ]
